name: dox_auth
description: Authentication package for dox framework with jsonwebtoken(jwt) driver.
version: 0.0.1
repository: https://github.com/dartondox/dox-auth

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dart_jsonwebtoken: ^2.8.2
  dox_query_builder: ^1.1.13
  dox_core: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
