name: dox_auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/dartondox/dox-auth

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.8.2

dev_dependencies:
  dox_query_builder: ^1.1.13
  dox_core: 
    path: /Users/zinkyawkyaw/projects/dart/dox-core
  lints: ^2.0.0
  test: ^1.21.0

